logging:
  
  # 10: debug, 20: info, 30: warning, 40: error
  level: 10

thethingsstack:
  
  # Host to use, if not defined will not change the user/system defined
  #host: "eu1.cloud.thethings.network"
  
  # Login using API-KEY, if not defined OAuth request will be triggered
  #apikey: "NNSXS.DWHQF...."
  
  # Application ID to export
  #application_id: "xp-airquality"
  
  # Export only devices updated since this long (number of seconds, 1h, 1d, 1w,... or the timestamps in ISO format)
  #active_since: "1h"

chirpstack:

  # Chirpstack server
  server: "localhost:8080"

  # API token with permissions on the application
  api_token: "eyJ0eXAiOi.....rb4"

  # Application EUI to save the devices to
  application_id: "023fddfb-db27-4c07-a151-1ef74b1e5908"
  
  # Device profile EUI to use when creating the devices
  device_profile_id: "4842e02c-07e8-4c0e-943e-692a52145e55"

# Folder used to export tiles
export_folder: "./"



